name: Build and tag CIMonitor container
on:
  workflow_call:
    inputs:
      BASE_IMAGE:
        description: Base build of what docker image
        required: true
        type: string
      DOCKER_DIRECTORY:
        description: Directory to get the docker files from
        required: true
        type: string
      DOCKER_IMAGE:
        description: Docker image tag to push into the docker hub
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
jobs:
  build-and-tag-container:
    name: Build & Tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install development dependencies
        run: yarn install --ignore-scripts

      - name: Build javascript application
        run: yarn build

      - name: Install production dependencies
        run: yarn install --production --ignore-scripts

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy Docker files
        run: cp ${{ inputs.DOCKER_DIRECTORY }}/Dockerfile ${{ inputs.DOCKER_DIRECTORY }}/.dockerignore .

      - name: Build and push CIMonitor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: production
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ inputs.DOCKER_IMAGE }}
          build-args: |
            BASE_IMAGE=${{ inputs.BASE_IMAGE }}
